/**
 * Terms of Service Page
 *
 * Comprehensive terms covering service usage, AI disclaimers,
 * intellectual property, liability limitations, and dispute resolution.
 * Last reviewed: January 2026
 */

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
      <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>

      <div className="prose prose-gray max-w-none space-y-6">
        <p className="text-gray-600">
          <strong>Effective Date:</strong> {new Date().toLocaleDateString()}
          <br />
          <strong>Last Updated:</strong> {new Date().toLocaleDateString()}
        </p>

        <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg mb-6">
          <p className="text-sm font-semibold text-yellow-900">IMPORTANT NOTICE</p>
          <p className="text-sm text-yellow-800 mt-2">
            These Terms contain a binding arbitration clause and class action waiver in Section 15.
            By using our Service, you agree to resolve disputes through individual arbitration
            rather than court proceedings or class actions.
          </p>
        </div>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
          <p>
            These Terms of Service (&quot;Terms&quot;) constitute a legally binding agreement between you and
            Authentyc AI, Inc. (&quot;Authentyc&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) regarding your access to and use
            of our website, services, and applications (collectively, the &quot;Service&quot;).
          </p>
          <p>
            By accessing or using the Service, you acknowledge that you have read, understood, and
            agree to be bound by these Terms and our{' '}
            <a href="/privacy" className="text-brand-primary underline">
              Privacy Policy
            </a>
            . If you do not agree to these Terms, you may not access or use the Service.
          </p>
          <p>
            <strong>Eligibility:</strong> You must be at least 18 years old to use this Service. By
            using the Service, you represent and warrant that you are 18 years of age or older.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">2. Description of Service</h2>
          <p>
            Authentyc provides AI-powered personality analysis and compatibility matching services.
            We analyze ChatGPT conversation patterns you voluntarily share to generate personality
            insights and suggest potential matches for hiring, dating, co-founder partnerships, and
            other relationship contexts.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">2.1 Beta/Waitlist Phase</h3>
          <p>
            The Service is currently in <strong>beta/waitlist phase</strong>. This means:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Features may be incomplete, experimental, or subject to change</li>
            <li>Service availability is not guaranteed</li>
            <li>We may invite users gradually based on waitlist position and feedback quality</li>
            <li>
              Some features (personality analysis preview) are available during waitlist; full
              matching features launch later
            </li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">2.2 Service Modifications</h3>
          <p>
            We reserve the right to modify, suspend, or discontinue any aspect of the Service at
            any time, with or without notice. We are not liable for any modification, suspension,
            or discontinuation of the Service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">
            3. AI-Generated Content Disclaimer
          </h2>

          <div className="p-4 bg-red-50 border border-red-200 rounded-lg my-4">
            <p className="font-semibold text-red-900">CRITICAL DISCLAIMER</p>
            <p className="text-sm text-red-800 mt-2">
              Authentyc&apos;s personality analyses and match suggestions are generated by artificial
              intelligence and are provided FOR ENTERTAINMENT AND EXPERIMENTAL PURPOSES ONLY. They
              are NOT professional advice and should not be used as the sole basis for important
              life decisions.
            </p>
          </div>

          <h3 className="text-xl font-semibold mt-6 mb-3">3.1 No Professional Advice</h3>
          <p>
            Our Service does <strong>NOT</strong> provide:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong>Medical or psychological advice:</strong> Our personality analyses are not
              psychological assessments and should not be used for diagnosis or treatment
            </li>
            <li>
              <strong>Employment advice:</strong> Hiring recommendations are experimental and should
              not replace proper background checks, interviews, or HR processes
            </li>
            <li>
              <strong>Relationship counseling:</strong> Dating insights are for entertainment and
              self-reflection, not professional matchmaking or therapy
            </li>
            <li>
              <strong>Legal or financial advice:</strong> Co-founder compatibility analyses are not
              due diligence or legal partnership counsel
            </li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">3.2 Accuracy & Limitations</h3>
          <p>You acknowledge and agree that:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              AI-generated personality insights are based on limited data (ChatGPT conversation
              patterns) and may be incomplete, inaccurate, or biased
            </li>
            <li>
              Personality is complex and cannot be fully captured by analyzing text conversations
            </li>
            <li>
              Match suggestions are algorithmic predictions, not guarantees of compatibility or
              success
            </li>
            <li>
              Our AI models may produce unexpected, incorrect, or inappropriate outputs despite our
              best efforts
            </li>
            <li>
              You should independently verify any information and use your own judgment before
              making decisions
            </li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">3.3 Third-Party AI Models</h3>
          <p>
            We use third-party AI services (OpenAI GPT-4o-mini, Google Gemini) to generate
            analyses. These models are subject to their own terms of service and limitations. We do
            not control the output of these models and disclaim responsibility for errors,
            omissions, or biases in AI-generated content.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">4. User Responsibilities</h2>

          <h3 className="text-xl font-semibold mt-6 mb-3">4.1 Account & Information Accuracy</h3>
          <p>You agree to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Provide accurate, current, and complete information (email, interests, etc.)</li>
            <li>Maintain the security of your account (if/when accounts are created)</li>
            <li>
              Notify us immediately of any unauthorized access or security breaches at{' '}
              <a href="mailto:legal@authentyc.ai" className="text-brand-primary underline">
                legal@authentyc.ai
              </a>
            </li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">4.2 Content You Share</h3>
          <p>
            When you share ChatGPT conversation links or other content with Authentyc, you
            represent and warrant that:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              You have the legal right to share the content (it&apos;s your conversation or you have
              permission)
            </li>
            <li>The content does not violate any third-party rights (privacy, copyright, etc.)</li>
            <li>
              The content does not contain illegal material, threats, harassment, hate speech, or
              other prohibited content
            </li>
            <li>
              You will not share conversations containing sensitive personal information about
              others without their consent
            </li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">4.3 Prohibited Conduct</h3>
          <p>You agree NOT to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              Use the Service for any unlawful purpose or in violation of these Terms or applicable
              laws
            </li>
            <li>
              Attempt to reverse engineer, decompile, or extract the source code of our Service or
              AI models
            </li>
            <li>
              Scrape, crawl, or use automated tools to access the Service beyond our published API
              (if any)
            </li>
            <li>
              Circumvent rate limits, security measures, or access controls (we limit analyses to 3
              per hour, 10 per day per IP)
            </li>
            <li>
              Create fake accounts, manipulate waitlist positions, or engage in fraudulent activity
            </li>
            <li>
              Interfere with or disrupt the Service, servers, or networks connected to the Service
            </li>
            <li>
              Use the Service to harass, stalk, threaten, or harm others, or to discriminate based
              on protected characteristics
            </li>
            <li>
              Resell, redistribute, or commercially exploit the Service without our written
              permission
            </li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">4.4 Compliance with Laws</h3>
          <p>
            You are solely responsible for ensuring your use of the Service complies with all
            applicable laws, including employment discrimination laws, data protection laws (GDPR,
            CCPA), and anti-harassment laws in your jurisdiction.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">5. Intellectual Property Rights</h2>

          <h3 className="text-xl font-semibold mt-6 mb-3">5.1 Ownership of Service</h3>
          <p>
            The Service, including all software, algorithms, design, text, graphics, logos, and
            other content (excluding user-generated content), is owned by Authentyc and protected
            by copyright, trademark, and other intellectual property laws. You may not copy,
            modify, distribute, or create derivative works without our written permission.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">5.2 Ownership of Analysis Data</h3>
          <p>
            As stated in our Privacy Policy, <strong>you own your personality analysis data</strong>
            . However, by using the Service, you grant Authentyc a non-exclusive, worldwide,
            royalty-free license to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Store, process, and display your analysis data to provide the Service to you</li>
            <li>
              Use aggregated, de-identified analysis data to improve our AI models, algorithms, and
              matching systems
            </li>
            <li>
              Analyze trends and patterns across multiple users for research and product development
            </li>
          </ul>
          <p>
            This license terminates when you delete your analysis data, except for de-identified
            data already incorporated into our models.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">5.3 Feedback & Suggestions</h3>
          <p>
            If you provide feedback, suggestions, or ideas about the Service (&quot;Feedback&quot;), you
            grant Authentyc a perpetual, irrevocable, worldwide, royalty-free license to use,
            modify, and incorporate Feedback into our Service without compensation or attribution.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">6. Privacy & Data Usage</h2>
          <p>
            Your privacy is important to us. Our collection, use, and disclosure of personal
            information is governed by our{' '}
            <a href="/privacy" className="text-brand-primary underline">
              Privacy Policy
            </a>
            , which is incorporated into these Terms by reference.
          </p>
          <p>Key points:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              We collect email, interests, ChatGPT conversation data (when shared), and analytics
            </li>
            <li>
              We use third-party services (OpenAI, Google Gemini, Supabase, Resend, PostHog,
              Vercel)
            </li>
            <li>Personality analyses are automatically deleted after 30 days</li>
            <li>We do not sell your personal information to third parties</li>
            <li>You can request deletion of your data at any time</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">7. Service Availability & Support</h2>

          <h3 className="text-xl font-semibold mt-6 mb-3">7.1 No Uptime Guarantees</h3>
          <p>
            The Service is provided on an &quot;as available&quot; basis. We do not guarantee the Service
            will be available 24/7, uninterrupted, or error-free. We may experience downtime for
            maintenance, upgrades, or due to factors beyond our control (third-party API outages,
            hosting issues, etc.).
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">7.2 Beta/Experimental Features</h3>
          <p>
            During the beta phase, features may be incomplete, buggy, or subject to change without
            notice. We make no commitments about feature availability, performance, or roadmap.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">7.3 Customer Support</h3>
          <p>
            We provide best-effort email support at{' '}
            <a href="mailto:legal@authentyc.ai" className="text-brand-primary underline">
              legal@authentyc.ai
            </a>
            . We aim to respond within 5 business days but do not guarantee response times or issue
            resolution.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">8. Fees & Payment (Future)</h2>
          <p>
            The Service is currently <strong>free during the waitlist/beta phase</strong>. We may
            introduce paid plans or premium features in the future. If we do:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>We will provide at least 30 days&apos; notice before charging existing users</li>
            <li>Pricing will be clearly disclosed on our website</li>
            <li>
              You will have the option to opt-out and delete your account before any charges occur
            </li>
            <li>All fees are non-refundable unless required by law</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">9. Termination</h2>

          <h3 className="text-xl font-semibold mt-6 mb-3">9.1 Termination by You</h3>
          <p>
            You may stop using the Service at any time. To delete your data, email{' '}
            <a href="mailto:privacy@authentyc.ai" className="text-brand-primary underline">
              privacy@authentyc.ai
            </a>
            .
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">9.2 Termination by Us</h3>
          <p>
            We may suspend or terminate your access to the Service at any time, with or without
            cause, with or without notice, including if:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>You violate these Terms or our Privacy Policy</li>
            <li>You engage in prohibited conduct (fraud, abuse, illegal activity)</li>
            <li>We discontinue the Service or cease operations</li>
            <li>Required by law or legal process</li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">9.3 Effect of Termination</h3>
          <p>Upon termination:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Your right to access and use the Service immediately ceases</li>
            <li>
              Your data will be deleted according to our Privacy Policy (waitlist data upon
              request, analysis data after 30 days)
            </li>
            <li>
              Sections 3 (AI Disclaimers), 5 (Intellectual Property), 10-16 (Liability,
              Indemnification, Disputes) survive termination
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">10. Disclaimers of Warranties</h2>
          <p>
            <strong>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS
              AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
            </strong>
          </p>
          <p>
            AUTHENTYC DISCLAIMS ALL WARRANTIES, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY WARRANTIES
            ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.
          </p>
          <p>Without limiting the foregoing, we do not warrant that:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>The Service will meet your requirements or expectations</li>
            <li>The Service will be uninterrupted, secure, or error-free</li>
            <li>
              AI-generated personality analyses will be accurate, reliable, or suitable for any
              purpose
            </li>
            <li>
              Match suggestions will result in successful relationships, hires, or partnerships
            </li>
            <li>Defects or errors will be corrected</li>
            <li>The Service is free from viruses or other harmful components</li>
          </ul>
          <p>
            Some jurisdictions do not allow disclaimers of implied warranties, so some of the above
            disclaimers may not apply to you.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">11. Limitation of Liability</h2>
          <p>
            <strong>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, AUTHENTYC AND ITS OFFICERS, DIRECTORS,
              EMPLOYEES, AGENTS, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA,
              OR USE, ARISING OUT OF OR RELATED TO THESE TERMS OR THE SERVICE, WHETHER BASED ON
              WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE, OR ANY OTHER LEGAL THEORY,
              EVEN IF AUTHENTYC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </strong>
          </p>
          <p>
            In no event shall Authentyc&apos;s total liability to you for all claims arising out of or
            related to these Terms or the Service exceed $100 USD or the amount you paid to us in
            the 12 months preceding the claim (whichever is greater).
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">11.1 Examples of Excluded Liability</h3>
          <p>Without limiting the above, we are not liable for:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              Decisions made based on AI-generated personality analyses or match suggestions (e.g.,
              hiring the wrong person, dating incompatible partners, choosing the wrong co-founder)
            </li>
            <li>
              Data breaches or security incidents at third-party services we use (OpenAI, Supabase,
              etc.)
            </li>
            <li>
              Harmful, offensive, or inaccurate AI-generated content (despite our content filters)
            </li>
            <li>
              Loss of business opportunities, reputation damage, or emotional distress arising from
              use of the Service
            </li>
            <li>
              Downtime, data loss, or service interruptions due to factors beyond our control
            </li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">11.2 State-Specific Exceptions</h3>
          <p>
            Some jurisdictions (e.g., New Jersey, California) do not allow limitations on implied
            warranties or exclusions of certain damages. In such jurisdictions, our liability is
            limited to the maximum extent permitted by law.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">12. Indemnification</h2>
          <p>
            You agree to indemnify, defend, and hold harmless Authentyc and its officers,
            directors, employees, agents, and affiliates from and against any claims, liabilities,
            damages, losses, costs, or expenses (including reasonable attorneys&apos; fees) arising out
            of or related to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Your use or misuse of the Service</li>
            <li>Your violation of these Terms</li>
            <li>Your violation of any third-party rights (privacy, intellectual property, etc.)</li>
            <li>
              Content you share with the Service (e.g., ChatGPT conversations containing
              third-party confidential information)
            </li>
            <li>
              Decisions you make based on AI-generated analyses (e.g., hiring, firing,
              relationship, or business decisions)
            </li>
          </ul>
          <p>
            We reserve the right to assume exclusive defense and control of any matter subject to
            indemnification, and you agree to cooperate with our defense of such claims.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">13. Third-Party Links & Services</h2>
          <p>
            The Service may contain links to third-party websites, services, or content (e.g.,
            ChatGPT, social media). We do not endorse, control, or assume responsibility for
            third-party content or services. Your use of third-party services is governed by their
            terms and privacy policies.
          </p>
          <p>
            Specifically, when you share ChatGPT conversation links, you are subject to OpenAI&apos;s
            Terms of Service and Sharing Policy. Ensure you have the right to share such
            conversations.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">
            14. DMCA & Intellectual Property Claims
          </h2>
          <p>
            If you believe content on our Service infringes your intellectual property rights,
            please contact us at{' '}
            <a href="mailto:legal@authentyc.ai" className="text-brand-primary underline">
              legal@authentyc.ai
            </a>{' '}
            with:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Description of the copyrighted work or intellectual property</li>
            <li>Location of the infringing material on our Service</li>
            <li>Your contact information (name, address, email, phone)</li>
            <li>
              A statement that you have a good faith belief the use is not authorized by the
              copyright owner
            </li>
            <li>
              A statement that the information in the notice is accurate and, under penalty of
              perjury, you are authorized to act on behalf of the owner
            </li>
            <li>Your physical or electronic signature</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">
            15. Dispute Resolution & Arbitration
          </h2>

          <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg my-4">
            <p className="font-semibold text-yellow-900">BINDING ARBITRATION CLAUSE</p>
            <p className="text-sm text-yellow-800 mt-2">
              This section contains a binding arbitration agreement and class action waiver. It
              affects your legal rights. Please read carefully.
            </p>
          </div>

          <h3 className="text-xl font-semibold mt-6 mb-3">15.1 Informal Dispute Resolution</h3>
          <p>
            Before filing a formal dispute, you agree to contact us at{' '}
            <a href="mailto:legal@authentyc.ai" className="text-brand-primary underline">
              legal@authentyc.ai
            </a>{' '}
            and attempt to resolve the dispute informally. We will attempt to resolve the dispute
            within 30 days.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">15.2 Binding Arbitration</h3>
          <p>
            If we cannot resolve the dispute informally, you and Authentyc agree that any claim,
            dispute, or controversy arising out of or relating to these Terms or the Service
            (collectively, &quot;Disputes&quot;) will be resolved by{' '}
            <strong>binding individual arbitration</strong> administered by the American
            Arbitration Association (AAA) under its Consumer Arbitration Rules, rather than in
            court.
          </p>
          <p>Key terms:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong>Individual Basis Only:</strong> Arbitration will be conducted on an
              individual basis, not as a class action, consolidated action, or representative
              action
            </li>
            <li>
              <strong>Location:</strong> Arbitration will take place in the county where you reside
              or via videoconference/telephone if you prefer
            </li>
            <li>
              <strong>Costs:</strong> Each party pays their own attorneys&apos; fees. Authentyc will pay
              AAA filing fees for claims under $10,000
            </li>
            <li>
              <strong>Governing Law:</strong> These Terms and any arbitration will be governed by
              the Federal Arbitration Act and Delaware law (excluding conflict-of-law principles)
            </li>
            <li>
              <strong>Arbitrator&apos;s Authority:</strong> The arbitrator may award the same relief as
              a court, but only to the individual party seeking relief
            </li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">15.3 Class Action Waiver</h3>
          <p>
            <strong>
              YOU AND AUTHENTYC AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR
              ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED
              CLASS, REPRESENTATIVE, OR PRIVATE ATTORNEY GENERAL ACTION.
            </strong>
          </p>
          <p>
            The arbitrator may not consolidate claims of multiple parties or preside over any form
            of representative or class proceeding. If this class action waiver is found
            unenforceable, the entire arbitration agreement (Section 15) is void, and Disputes will
            be resolved in court.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">15.4 Exceptions to Arbitration</h3>
          <p>The following Disputes are exempt from arbitration and may be litigated in court:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Claims for injunctive or equitable relief to protect intellectual property</li>
            <li>Small claims court actions (if they remain in small claims court)</li>
            <li>Claims that cannot be arbitrated under applicable law</li>
          </ul>

          <h3 className="text-xl font-semibold mt-6 mb-3">15.5 Opt-Out Right</h3>
          <p>
            You may opt out of this arbitration agreement within 30 days of first accepting these
            Terms by emailing{' '}
            <a href="mailto:legal@authentyc.ai" className="text-brand-primary underline">
              legal@authentyc.ai
            </a>{' '}
            with subject line &quot;Arbitration Opt-Out&quot; and including your name and email address. If
            you opt out, all other terms still apply, but disputes will be resolved in court.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">16. Governing Law & Jurisdiction</h2>
          <p>
            These Terms are governed by the laws of the State of Delaware, United States, without
            regard to conflict-of-law principles. Subject to the arbitration agreement in Section
            15, any disputes not subject to arbitration shall be resolved exclusively in the state
            or federal courts located in Delaware, and you consent to personal jurisdiction in such
            courts.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">17. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time to reflect changes in our Service, legal
            requirements, or business practices. We will notify you of material changes by:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Updating the &quot;Last Updated&quot; date at the top of these Terms</li>
            <li>Sending an email to registered users (for material changes)</li>
            <li>Displaying a prominent notice on our website</li>
          </ul>
          <p>
            Your continued use of the Service after changes are posted constitutes your acceptance
            of the updated Terms. If you do not agree to the updated Terms, you must stop using the
            Service.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">18. General Provisions</h2>

          <h3 className="text-xl font-semibold mt-6 mb-3">18.1 Entire Agreement</h3>
          <p>
            These Terms, together with our Privacy Policy, constitute the entire agreement between
            you and Authentyc regarding the Service and supersede all prior agreements or
            understandings.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">18.2 Severability</h3>
          <p>
            If any provision of these Terms is found invalid or unenforceable, the remaining
            provisions will remain in full force and effect, and the invalid provision will be
            modified to reflect the parties&apos; intent to the maximum extent permitted by law.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">18.3 Waiver</h3>
          <p>
            Our failure to enforce any right or provision of these Terms does not constitute a
            waiver of that right or provision. Any waiver must be in writing and signed by
            Authentyc.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">18.4 Assignment</h3>
          <p>
            You may not assign or transfer these Terms or your rights under these Terms without our
            written consent. We may assign these Terms (e.g., in connection with a merger or
            acquisition) without your consent.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">18.5 Force Majeure</h3>
          <p>
            We are not liable for delays or failures in performance due to causes beyond our
            reasonable control, including acts of God, natural disasters, war, terrorism, labor
            disputes, third-party service outages (AWS, OpenAI, etc.), or government restrictions.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-3">18.6 Export Controls</h3>
          <p>
            The Service may be subject to U.S. export control laws. You agree to comply with all
            applicable export and import laws and regulations. You may not use the Service if you
            are located in a country embargoed by the United States or are on a U.S. government
            restricted party list.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mt-8 mb-4">19. Contact Information</h2>
          <p>If you have questions or concerns about these Terms, please contact us:</p>
          <div className="mt-4">
            <p>
              <strong>Email:</strong>{' '}
              <a href="mailto:legal@authentyc.ai" className="text-brand-primary underline">
                legal@authentyc.ai
              </a>
            </p>
            <p>
              <strong>Company:</strong> Authentyc AI, Inc.
            </p>
            <p>
              <strong>Attention:</strong> Legal Department
            </p>
          </div>
        </section>

        <div className="mt-12 p-4 bg-gray-50 border border-gray-200 rounded-lg">
          <p className="text-sm text-gray-600">
            <strong>Legal Review Recommended:</strong> These Terms were drafted based on industry
            best practices and standard legal protections for AI/SaaS products. However, they
            should be reviewed by a licensed attorney familiar with technology law, AI liability,
            and your specific jurisdiction before launch. Consider additional provisions for
            employment discrimination (if hiring use case), GDPR compliance (if targeting EU
            users), or sector-specific regulations.
          </p>
        </div>

        <div className="mt-4 p-4 bg-blue-50 border border-blue-200 rounded-lg">
          <p className="text-sm text-blue-900">
            <strong>User-Friendly Summary (Not Legally Binding):</strong>
          </p>
          <ul className="text-sm text-blue-800 mt-2 space-y-1 list-disc pl-6">
            <li>Our AI personality analyses are for entertainment/experimental purposes only</li>
            <li>Don&apos;t use our Service as the sole basis for important life decisions</li>
            <li>
              You own your data, but we can use aggregated insights to improve our algorithms
            </li>
            <li>
              Disputes are resolved through individual arbitration, not class action lawsuits
            </li>
            <li>
              We&apos;re not liable for decisions you make based on AI-generated insights (hiring,
              dating, etc.)
            </li>
            <li>Read the full Terms above for complete legal details</li>
          </ul>
        </div>
      </div>
    </div>
  );
}
